import Head from "next/head";
import { useState, useEffect } from "react";
import Tables from "../components/Table";

export default function Home() {
  const [userData, setUserData] = useState();
  
  const mount = async () => {
    await fetch("/api/User")
    .then(res => res.json())
    .then(response => setUserData(response.data))
  }

  useEffect(()=>{
    mount()
  },[])

  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="mt-6">
        <Tables user={userData} mount={mount} />
      </div>
    </>
  );
}
